import { stringify } from "https://esm.sh/yaml@v2.3.1";
import Job from "./job.ts";
import { YamlSpec, Variable, Include } from "./gitlabci_spec.ts";

class GitlabCI {
  private yaml: YamlSpec;

  constructor() {
    this.yaml = [];
  }

  addJob(name: string, job: Job): GitlabCI {
    this.yaml.push({
      [name]: job.into(),
    });
    return this;
  }

  stages(stages: string[]): GitlabCI {
    this.yaml.push({
      stages,
    });
    return this;
  }

  variable(name: string, value: string): GitlabCI {
    if (this.yaml.find((item) => (item as { variables: Variable }).variables)) {
      (
        this.yaml.filter(
          (item) => (item as { variables: Variable }).variables
        )[0] as { variables: Variable }
      ).variables[name] = value;
      return this;
    }
    this.yaml.push({
      variables: {
        [name]: value,
      },
    });

    return this;
  }

  variables(variables: Variable): GitlabCI {
    if (this.yaml.find((item) => (item as { variables: Variable }).variables)) {
      const { variables: vars } = this.yaml.filter(
        (item) => (item as { variables: Variable }).variables
      )[0] as {
        variables: Variable;
      };
      Object.assign(vars, variables);
      return this;
    }
    this.yaml.push({
      variables,
    });
    return this;
  }

  cache(paths: string[], key?: string): GitlabCI {
    this.yaml.push({
      cache: {
        paths,
        key,
      },
    });
    return this;
  }

  comment(text: string): GitlabCI {
    text = text.trim();
    text
      .split("\n")
      .map((line) => line.trim())
      .map((line) =>
        line.length > 0 ? this.yaml.push(`# ${line}`) : this.yaml.push("")
      );
    return this;
  }

  include(value: { template: string }) {
    if (this.yaml.find((item) => (item as { include: Include }).include)) {
      const { include } = this.yaml.filter(
        (item) => (item as { include: Include }).include
      )[0] as {
        include: Include;
      };
      if (include instanceof Array) {
        include.push(value);
      }
      return this;
    }
    this.yaml.push({
      include: [value],
    });
    return this;
  }

  toString() {
    let str = `# Do not edit this file directly. It is generated by Fluent GitLab CI\n\n`;

    for (const item of this.yaml) {
      if (typeof item === "string") {
        str += `${item}\n`;
        continue;
      }
      str += `${stringify(item)}\n`;
    }

    return str.replaceAll(" {}", "");
  }

  newLine() {
    this.yaml.push("");
    return this;
  }

  toFile(path = ".gitlab-ci.yml") {
    const config = this.toString();
    Deno.writeTextFileSync(path, config);
  }
}

export default GitlabCI;
